apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superops.fullname" . }}-secret
  labels:
    {{- include "superops.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.auth.rootUser | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.auth.rootPassword | quote }}
  MEILI_MASTER_KEY: {{ .Values.meilisearch.masterKey | quote }}
